# This is a basic workflow to help you get started with Actions

name: Push to CriblWorkerGroups

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test and main" branch
  push:
    branches:
      - test
      - main
  pull_request:
    branches:
      - test
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run of the jobs needed to deploy to Cribl Worker Groups and Workspaces
jobs:
  # This workflow contains a single job called "deploy-to-Test" which deploys to Cribl Test Worker Groups
  deploy-to-test:
    if: github.ref == 'refs/heads/test'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v4
      # Installs packs across worker groups
      - name: Install pack across worker groups
        env:
          CRIBL_CLIENT_ID: ${{ secrets.CRIBL_CLIENT_ID }}
          CRIBL_CLIENT_SECRET: ${{ secrets.CRIBL_CLIENT_SECRET }}
          CRIBL_ENDPOINT: ${{ vars.TEST_ENDPOINT }}
          CRIBL_WG_LIST: test_worker_groups.txt
          PACK_REPO_HTTPS_URL: git+${{github.server_url}}/${{github.repository}}.git
          PACK_REPO_SSH_URL: "https://${{  github.repository_owner  }}:${{  secrets.REPO_PERSONAL_ACCESS_TOKEN  }}@github.com/${{  github.repository  }}.git"
          OVERRIDE: true
          PACK_BRANCH: test
        run: |
          echo "$PACK_REPO_SSH_URL"
          # # WG_LIST="$(pwd)/test_worker_groups.txt"
          # WG_LIST="$(pwd)/$CRIBL_WG_LIST"
          # ACCESS_TOKEN=$(curl -X POST "https://login.cribl.cloud/oauth/token" \
          # -H "Content-Type: application/json" \
          # -d "{\"grant_type\": \"client_credentials\",\"client_id\": \"$CRIBL_CLIENT_ID\", \"client_secret\": \"$CRIBL_CLIENT_SECRET\", \"audience\": \"https://api.cribl.cloud\"}" \
          # | jq -r '.access_token')
          # while IFS= read -r WORKERGROUP || [[ -n "$WORKERGROUP" ]]; do
          #   MAIN_ENDPOINT="$CRIBL_ENDPOINT"
          #   WG_ENDPOINT="$MAIN_ENDPOINT/$WORKERGROUP/packs"
          #   curl -X POST "$WG_ENDPOINT" \
          #   -H "Authorization: Bearer $ACCESS_TOKEN" \
          #   -H 'Content-Type: application/json' \
          #   -d "{\"source\": \"$PACK_REPO_SSH_URL\",\"force\":$OVERRIDE,\"spec\":\"$PACK_BRANCH\",\"allowCustomFunctions\":false}"
          # done < "$WG_LIST"
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v4
      # Installs packs across worker groups
      - name: Install pack across worker groups
        env:
          CRIBL_CLIENT_ID: ${{ secrets.CRIBL_CLIENT_ID }}
          CRIBL_CLIENT_SECRET: ${{ secrets.CRIBL_CLIENT_SECRET }}
          CRIBL_ENDPOINT: ${{ vars.PROD_ENDPOINT }}
          CRIBL_WG_LIST: prod_worker_groups.txt
          PACK_REPO_HTTPS_URL: ${{github.server_url}}/${{github.repository}}.git
          PACK_REPO_SSH_URL: git@github.com:${{github.repository}}.git
          OVERRIDE: true
          PACK_BRANCH: main
        run: |
          # WG_LIST="$(pwd)/prod_worker_groups.txt"
          echo "${{github.repository}}"
          echo "${{github.repository.id}}"
          WG_LIST="$(pwd)/$CRIBL_WG_LIST"
          ACCESS_TOKEN=$(curl -X POST "https://login.cribl.cloud/oauth/token" \
          -H "Content-Type: application/json" \
          -d "{\"grant_type\": \"client_credentials\",\"client_id\": \"$CRIBL_CLIENT_ID\", \"client_secret\": \"$CRIBL_CLIENT_SECRET\", \"audience\": \"https://api.cribl.cloud\"}" \
          | jq -r '.access_token')
          while IFS= read -r WORKERGROUP || [[ -n "$WORKERGROUP" ]]; do
            MAIN_ENDPOINT="$CRIBL_ENDPOINT"
            WG_ENDPOINT="$MAIN_ENDPOINT/$WORKERGROUP/packs"
            curl -X POST "$WG_ENDPOINT" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H 'Content-Type: application/json' \
            -d "{\"source\": \"git+$PACK_REPO_SSH_URL\",\"force\":$OVERRIDE,\"spec\":\"$PACK_BRANCH\",\"allowCustomFunctions\":false}"
            # -d '{"source": "git+https://github.com/criblpacks/cribl-splunk-uf-internal-redux.git","force":true,"spec":"main","allowCustomFunctions":false}'
          done < "$WG_LIST"
