# This is a basic workflow to help you get started with Actions

name: Push to CriblWorkerGroups

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test and main" branch
  push:
    branches:
      - test
      # - main
  pull_request:
    branches:
      - test
      # - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run of the jobs needed to deploy to Cribl Worker Groups and Workspaces
jobs:
  # This workflow contains a single job called "deploy-to-Test" which deploys to Cribl Test Worker Groups
  deploy-to-test:
    if: github.ref == 'refs/heads/test'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v4
      # Installs packs across worker groups
      - name: Install pack across worker groups
        env:
          CRIBL_CLIENT_ID: ${{ secrets.CRIBL_CLIENT_ID }}
          CRIBL_CLIENT_SECRET: ${{ secrets.CRIBL_CLIENT_SECRET }}
          CRIBL_ENDPOINT: ${{ vars.TEST_ENDPOINT }}
          CRIBL_WG_LIST: test_worker_groups.txt
          PACK_REPO_HTTPS_URL: git+${{github.server_url}}/${{github.repository}}.git
          PACK_REPO_SSH_TOKEN: ${{  secrets.REPO_PERSONAL_ACCESS_TOKEN  }}
          REPO_OWNER: ${{  github.repository_owner  }}
          REPO_NAME: ${{  github.repository  }}
          # Set the install type to override the install if a pack exists in a destination worker group
          OVERRIDE: true
          # Set the branch of the pack to push to the worker groups
          PACK_BRANCH: test
          # Set to true if using a public repo and false if using a private repo
          PUBLIC_REPO: false
        run: |
          ./install.sh
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v4
      # Installs packs across worker groups
      - name: Install pack across worker groups
        env:
          CRIBL_CLIENT_SECRET: ${{ secrets.CRIBL_CLIENT_SECRET }}
          CRIBL_ENDPOINT: ${{ vars.TEST_ENDPOINT }}
          CRIBL_WG_LIST: prod_worker_groups.txt
          PACK_REPO_HTTPS_URL: git+${{github.server_url}}/${{github.repository}}.git
          PACK_REPO_SSH_TOKEN: ${{  secrets.REPO_PERSONAL_ACCESS_TOKEN  }}
          REPO_OWNER: ${{  github.repository_owner  }}
          REPO_NAME: ${{  github.repository  }}
          # Set the install type to override the install if a pack exists in a destination worker group
          OVERRIDE: true
          # Set the branch of the pack to push to the worker groups
          PACK_BRANCH: main
          # Set to true if using a public repo and false if using a private repo
          PUBLIC_REPO: false
        run: |
          ./install.sh
